name: Manual workflow

on:
  workflow_dispatch:
    inputs:

jobs:
  display_env_var_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Display trigger type
        run: echo $GITHUB_EVENT_NAME
    
