name: push pull trigger test

on:
  workflow_dispatch:
     inputs:

env:
  at_least_one_job_ran: false

jobs:
  display_env_var_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Display trigger type
      - run: echo "{{ $github.event_name }}"

      - name: Display variables
      - run: env

      - name: Confirm job ran
      - run: |
          echo "{at_least_one_job_ran}={true}" >> $GITHUB_ENV"
      
  display_env_var_push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Display trigger type
      - run: echo "{{ $github.event_name }}"

      - name: Display variables
      - run: env

      - name: Confirm job ran
      - run: |
          echo "{at_least_one_job_ran}={true}" >> $GITHUB_ENV"
      
  run_parallel:
      runs-on: ubuntu-latest
      steps:
      - name: Display trigger type in parallel
      - run: echo "{{ $github.event_name }}"

      - name: Display variables
      - run: env

      - name: Confirm job ran
      - run: |
          echo "{at_least_one_job_ran}={true}" >> $GITHUB_ENV"
  run_if_any:
      runs-on: ubuntu-latest
      if: ${{ env.at_least_one_job_ran }}

      steps:
      - name: Display trigger type in parallel
      - run: echo "At least one of the jobs finished successfully"
      
